obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.33, -0.19], [-0.33, 0.19], [0.1, 0.19], [0.1, -0.19]]
#robot_radius:

inflation_radius: 1.0
cost_scaling_factor: 3.0

map_type: costmap

obstacle_layer:
  observation_sources: scan obstacle_scan
  scan: {sensor_frame: base_scan_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
  obstacle_scan: {sensor_frame: obstacle_scan_link, data_type: LaserScan, topic: obstacle_scan, marking: true, clearing: true}
