jobs:
  build:
    working_directory: /catkin_ws/src
    docker:
      - image: ros:kinetic-ros-core-xenial

    steps:
      - checkout
      - run:
          command: |
            apt-get update
            apt-get install -y ros-kinetic-tf
      - run:
          command: |
            source /opt/ros/kinetic/setup.bash
            catkin_init_workspace
            cd ..
            catkin_make run_tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build